In [1]:
import numpy as np

In [191]:
A = np.loadtxt("in20-test.txt", dtype=int)
L = len(A)
B = np.vstack((A, np.arange(L))).T

In [192]:
B

array([[ 1,  0],
       [ 2,  1],
       [-3,  2],
       [ 3,  3],
       [-2,  4],
       [ 0,  5],
       [ 4,  6]])

In [214]:
B[(B[:, 1] >= idx) * (B[:, 1] < new_idx),0]

array([ 2,  3, -2])

In [219]:
A

array([ 1,  2, -3,  3, -2,  0,  4])

In [224]:
A = np.array([0,0,1,-1])

In [264]:
A = np.loadtxt("in20.txt", dtype=int)
L = len(A)
B = np.vstack((A, np.arange(L))).T


print(np.array(sorted(B.tolist(), key=lambda x: x[1]))[:, 0])

for n, (num, idx) in enumerate(B):
    idx = B[n, 1]

    new_idx = idx + num
    if new_idx <= 0:
        # it goes down
        new_idx = (L - 1) + new_idx
    else:
        # it goes up
        new_idx %= L

#     print("will move down", B[(B[:, 1] > idx) * (B[:, 1] <= new_idx), 0])
#     print("will move up  ", B[(B[:, 1] <= idx + 1) * (B[:, 1] > new_idx + 1), 0])
#     print(num, ": ", idx, "->", new_idx)

    B[(B[:, 1] > idx) * (B[:, 1] <= new_idx), 1] -= 1
    B[(B[:, 1] <= idx + 1) * (B[:, 1] > new_idx + 1), 1] += 1
    B[n, 1] = new_idx

#     print(np.array(sorted(B.tolist(), key=lambda x: x[1]))[:, 0])
#     print(sorted(B[:, 1]), "all idxs")
#     print()


# print(sorted(B[:, 1]))
res = np.array(sorted(B.tolist(), key=lambda x: x[1]))[:, 0]
print(res)

[-8622 -8082 -2786 ... -4339 -7936  6742]
[-4953, -4927, -4919, -4891, -4885, -4867, -4770, -4722, -4675, -4668, -4662, -4654, -4633, -4632, -4618, -4612, -4604, -4591, -4559, -4556, -4526, -4513, -4488, -4480, -4459, -4446, -4422, -4410, -4404, -4394, -4393, -4368, -4357, -4343, -4336, -4336, -4334, -4320, -4307, -4288, -4279, -4276, -4253, -4223, -4194, -4191, -4182, -4176, -4172, -4166, -4109, -4086, -4081, -4080, -4073, -4072, -4063, -4023, -4017, -4015, -4005, -3970, -3963, -3950, -3944, -3932, -3930, -3923, -3922, -3913, -3900, -3891, -3882, -3866, -3857, -3856, -3821, -3814, -3812, -3806, -3800, -3795, -3779, -3760, -3757, -3749, -3748, -3745, -3740, -3740, -3733, -3728, -3717, -3717, -3705, -3701, -3696, -3685, -3680, -3672, -3665, -3656, -3651, -3649, -3636, -3636, -3635, -3629, -3628, -3615, -3608, -3607, -3599, -3598, -3589, -3589, -3569, -3559, -3556, -3550, -3527, -3519, -3516, -3502, -3499, -3488, -3487, -3481, -3463, -3460, -3459, -3457, -3449, -3445, -3430, -3429, -3412

In [265]:
bias = np.where(res==0)[0][0]
sum((res[(bias+1000)%L],res[(bias+2000)%L],res[(bias+3000)%L]))

-10513

In [240]:
print("will move up  ", B[(B[:, 1] <= idx + 1) * (B[:, 1] > new_idx + 1), 0])

will move up   [1]


In [107]:
np.array(sorted(B.tolist(),key=lambda x:x[1]))[:,0]

array([ 1, -3,  2,  3, -2,  0,  4])

In [55]:
print(B[new_idx+1:])

[[-3  1]
 [ 3  3]
 [-2  4]
 [ 0  5]
 [ 4  6]]


In [50]:
B

array([[ 1,  1],
       [ 2,  1],
       [-3,  1],
       [ 3,  3],
       [-2,  4],
       [ 0,  5],
       [ 4,  6]])